- src/api/controllers/dummy.controller.ts
- src/api/routes/dummy.routes.ts
- src/api/routes/index.routes.ts
- src/core/app/services/dummy.services.ts
- src/core/errors/core/base-error.error.ts
- src/core/errors/not-found.error.ts
- src/core/infra/repositories/__tests__/dummyRepository.spec.ts
- src/core/infra/repositories/dummy.respository.ts
- src/index.ts
Transitioned from an Object-Oriented Programming paradigm to a streamlined script-based approach, effectively reducing project complexity.
> chore(Project): removed OOP approach

- db/link_bridge_db.sql
- prisma/schema.prisma
Agregar estado de archivado o no archivado a la tabla de “company”
Agregar a la tabla de proyectos si pertenecen a legal o a contable.
> actualizacion de las tablas company y project

- package.json
- pnpm-lock.yaml
Añadir la libreria de dotenv para leer el archivo
> fix(dotenv): add dotenv to library

- .github/actions/develop.yml
- .github/actions/staging.yml
Ajustar para que github actions corra sin problema
> fix(dev): fix yaml file

- package.json
- src/index.ts
> Added cors

- .mocharc.json
- package.json
- src/core/app/services/__tests__/dummy.service.test.ts
Ajustes para que los test corran en el dir correcto
> fix(tests): fix tests

- src/api/controllers/employee.controller.ts
- src/api/routes/employee.routes.ts
- src/core/app/services/__tests__/employee.service.test.ts
- src/core/app/services/employee.service.ts
- src/core/infra/repositories/employee.repository.ts
[Feature/51]: Fetch todos los usuarios
- Endpoint para hacer fetch de todos los usuarios en un arreglo de objetos
7
@sebFlores02 -> Pendiente
> RF51: Find all employees

- src/api/controllers/project.controller.ts
- src/api/routes/project.routes.ts
- src/core/app/services/project.services.ts
- src/core/infra/repositories/project.repository.ts
[Feature/Task ID]: fix/RF14:Fixing orderBy and adding documentation
Fixing orderBy and adding documentation
- project.routes.ts
- project.services.ts
- project.repository.ts
- project.controller.ts
1
No se editaron las pruebas
Cualquier información adicional que el revisor o el autor del PR necesite saber. Aquí es donde se puede incluir imagenes, gifs, etc.
> fix(fixingOrderRF14): Fixing orderBy and adding documentation

- src/core/infra/mappers/department-entity-from-db-model.mapper.ts
- src/core/infra/mappers/role-entity-from-db-model.mapper.ts
Cambio necesario para login pueda funcionar
- Se arreglo el mapper de role y department
> fix(mapper): fix mapper

- src/core/app/services/employee.service.ts
- src/utils/enums/index.ts
- src/core/app/services/employee.service.ts
- src/utils/enums/index.ts
> fix(rbac): fix matching roles

- src/api/controllers/admin.controller.ts
- src/api/routes/admin.routes.ts
- src/core/app/services/__tests__/admin-role.service.test.ts
- src/core/app/services/admin-role.service.ts
- src/utils/enums/index.ts
Esta función trae a todos los roles, ya que el requisito funcional de actualizar rol pues necesitábamos saber cuáles eran todos los roles para poner el dropdown.
- Añadimos el endpoint ```GET /admin/roles```
> Get all roles

- src/api/controllers/project.controller.ts
[RF28]: Agarrar date desde req.query
Facilitar la conexión front-back
> fix(backend): req.query.date in project report

- src/core/app/services/__tests__/project.service.test.ts
- src/core/app/services/employee.service.ts
- src/utils/enums/index.ts
- Quitar el toUpperCase en los roles
- Editar los enums para que tengan el formato correcto
> fix(enums): fix role enums

- src/api/controllers/home.controller.ts
- src/api/routes/home.routes.ts
- src/api/routes/index.routes.ts
- src/core/app/interfaces/home.interface.ts
- src/core/app/services/__tests__/home.service.test.ts
- src/core/app/services/home.service.ts
- src/core/app/services/task.service.ts
- src/core/infra/repositories/tasks.repository.ts
[Feature/RF62]: Consultar proyectos y clientes
Se obtienen los proyectos en los que participa el usuario y las compañías asociadas.
Se crearon/actualizaron los siguientes archivos:
- index.routes.ts
- home.routes.ts
- home.controller.ts
- home.service.ts
- home.interface.ts
- home.service.test.ts
13
Se incluyen pruebas unitarias para un caso exitoso y el manejo de errores.
Ninguna
Ninguna
> feat(backend): homepage info

- src/core/app/services/home.service.ts
[Feature/Task 62]: Fix
Se agregaron las horas cobrables a la informacion de cada cliente
- home.service.ts
> fix(service): horas cobrables en company

- src/core/infra/repositories/project.repository.ts
[Feature/Task ID]: Descripción del cambio
Order projects by status
- src/core/infra/repositories/project.repository.ts
3
[ ] Se muestra la pantalla con la lista de todos los proyectos ordenados por status (el status de “Done” debe de ser el último que aparece).
NA
> fix(projects): order projects by status

- src/api/controllers/project.controller.ts
- src/api/routes/project.routes.ts
- src/core/app/services/project.service.ts
- src/core/infra/repositories/project.repository.ts
FIX: Los proyectos en done ahora salen al final por [defecto](https://github.com/orgs/Black-Dot-2024/projects/7/views/2?pane=issue&itemId=61734965)
- Project Repository
#150
> Proyectos en "Done" salen al final

- src/api/controllers/project.controller.ts
- src/api/routes/project.routes.ts
- src/core/app/services/project.service.ts
- src/core/infra/repositories/project.repository.ts
Ahora solo se pueden consultar los proyectos de tu departamento
> fix(projects): you can only see department projects

- src/core/app/services/__tests__/project.service.test.ts
[Fix/RF19]: Test
Correcion del test
- project.service.test.ts
> fix(test): hardcoded ids

- src/api/controllers/project.controller.ts
- src/core/infra/repositories/employee-task.repository.ts
- src/core/infra/repositories/project.repository.ts
- src/core/infra/repositories/tasks.repository.ts
[Feature/Task ID]: Eliminar console logs y errors
Se eliminaron los logs del backend
https://github.com/Black-Dot-2024/Zeitgeist-Backend/issues/106
> fix(backend): logs and errors

- src/api/controllers/task.controller.ts
- src/api/routes/task.routes.ts
- src/core/app/services/__tests__/task.services.test.ts
- src/core/app/services/task.service.ts
- src/core/infra/repositories/tasks.repository.ts
[RF03]: Task status now PUTs to backend when updated
Se agregó la funcionalidad de actualización de estatus de tarea en la vista de detalle de proyectos.
- Se actualizó el componente TaskListTable
- Se hace una request tipo PUT usando axios con el estado actualizado
- Se creó la prueba unitaria para esta funcionalidad
5
- Not started
- In process
- Under revision
- Delay
- Postponed
- Done
- Cancelled 
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/93755653/2721a234-d6e0-4b85-b653-5ef0ba1ed172
> RF03: Update Task Status

- src/api/routes/admin.routes.ts
- src/api/routes/company.routes.ts
- src/api/routes/employee.routes.ts
- src/api/routes/notification.routes.ts
- src/api/routes/project.routes.ts
- src/api/routes/task.routes.ts
[Refactor/routes]: Normalizar las rutas y el orden en que las codificamos dentro del Backend
Se intenta llevar un estándar para las rutas:
1. `get`
2. `put`
3. `post`
4. `delete`
En cada una de estas, también se ordena:
1. `/`
2. `/<ruta>`                         
- Ej.: `/update`
4. `/<ruta>/:<params>`      
- Ej.: `/update/:id`
6. `/:<params>`                   
- Ej.: `/:id`
- Actualizar archivos de rutas
\-
\-
\-
Ninguna
> refactor(routes): Updated routes orderings

- src/core/app/services/__tests__/company.service.test.ts
- src/core/app/services/company.service.ts
- src/core/domain/entities/company.entity.ts
- src/core/domain/entities/project.entity.ts
- src/core/infra/mappers/company-entity-from-db-model.mapper.ts
- src/core/infra/repositories/company.repository.ts
- src/core/infra/repositories/project.repository.ts
[Feature/Task ID]: Descripción del cambio
Arreglar el cálculo de horas y proyectos para cada cliente
> fix(hours): fix calc of hours and projects for companies

- src/core/app/services/home.service.ts
[Feature/Task 62]:
Las horas cobrables de un cliente se calcula a partir de las tareas de los prpyectos del cliente
> fix(service): horas cobrables

- package.json
- pnpm-lock.yaml
- src/utils/logger.ts
> Add colors to logger

- src/api/routes/employee.routes.ts
[Feature/Task ID]: Descripción del cambio
Nuevo endpoint para los tres roles: Admin, Accounting y Legal para consultar la lista de empleados.
- employee.routes.ts
> fix(createTask): new endpoint for create task

- src/core/infra/repositories/company.repository.ts
Correccion del conteo de horas de contable y legal por cliente
> fix(backend): count department hours

- src/api/middlewares/auth.middleware.ts
https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/pull/474
> fix(status): add 401 for un authorize

- src/api/controllers/project.controller.ts
- src/core/app/services/__tests__/project.service.test.ts
- src/core/app/services/project.service.ts
Cuando un empleado consulta los detalles de un cliente, solo puede visualizar los proyectos que son de su area.
Se resuelve el issue: https://github.com/Black-Dot-2024/Zeitgeist-Backend/issues/189
> fix(RBAC): service

- src/core/app/services/company.service.ts
Poder enviar una fecha nula
- https://github.com/orgs/Black-Dot-2024/projects/7/views/1?pane=issue&itemId=62816707
- Usar `No date` para cuando no haya una fecha
- Poder enviar una fecha nula
[Screen Recorder (1).webm](https://github.com/Black-Dot-2024/Zeitgeist-FrontEnd/assets/81983296/875149fd-bf68-4dd7-b02a-4e0048d5847a)
> fix(date): constitution date

- src/api/controllers/admin.controller.ts
- src/api/controllers/department.controller.ts
- src/api/routes/department.routes.ts
- src/api/routes/index.routes.ts
- src/core/app/services/admin-role.service.ts
- src/core/app/services/department.service.ts
- src/core/infra/repositories/department.repository.ts
Al momento de cambiar el rol de un usuario, se asigna el departamento correspondiente.
- Closes: #410
> fix(assignDepartment): now assigns department without destroying the DB

- src/api/controllers/project.controller.ts
- src/api/controllers/task.controller.ts
- src/core/app/services/__tests__/project.service.test.ts
- src/core/app/services/__tests__/task.services.test.ts
- src/core/app/services/project-report.service.ts
- src/core/app/services/project.service.ts
- src/core/app/services/task.service.ts
[Feature/Task ID]: Descripción del cambio
Se agrega a lso servicios de findProjectById y getTaskByProject el RBAC. Solo usuarios de contable pueden acceder a proyectos de contable y lo mismo con legal. 
Los administradores tienen acceso a todo.
> fix(service): RBAC

- src/api/controllers/company.controller.ts
- src/api/routes/company.routes.ts
- src/api/validators/company.validator.ts
- src/api/validators/zod.validator.ts
- src/core/infra/repositories/company.repository.ts
- Se cambiaron endpoints de crear clientes
> fix(clientForm): correctly parse the data

- src/core/app/services/__tests__/task.services.test.ts
- src/core/app/services/task.service.ts
> fix(tests): fix tests for tasks

- pnpm-lock.yaml
- prisma/migrations/20240522045959_expenses_update_fields/migration.sql
- prisma/migrations/20240524081944_add_missing_fields_for_expense_and_expense_report/migration.sql
Se añadieron las migraciones perdidas por el roll-back a develop.
> Añadir migraciones faltantes

- src/api/controllers/company.controller.ts
- src/api/validators/zod.validator.ts
Se modificó el límite de caracteres que se pueden introducir en el campo de email de un cliente. Se hicieron también pequeños cambios de documentación de código.
- Se modificó el archivo ```src/api/controllers/company.controller.ts```
- Se modificó el archivo ```src/api/validators/zod.validator.ts```
N/A
> fix(RF19): Email is now capped to 70 characters
